### ISSUE TITLE
Implement Candidate Search

### ISSUE THREAD

**Issue by davidsilvasmith** [checkr/checkr-ruby#23]
I don't see a way to find candidates other than by ID.

The api has a search that takes criteria like this:

`curl -X GET https://api.checkr.com/v1/candidates -u 83ebeabdec09f6670863766f792ead24d61fe3f9: -d first_name=John`

But that is not implemented (as far as I can tell in candidates.rb.

**Comment by cjford** [comment]
Not sure what this looked like when the issue was first opened, but regarding the current functionality: Search parameters are supported on the candidate list endpoint, however `first_name` is not one of the searchable fields. You can use `full_name` instead.

Here is the documentation listing the accepted parameters: https://docs.checkr.com/#operation/listOfCandidates

You can pass them into the candidate call like so: 
`Checkr::Candidate.all(full_name: 'John Doe')`
